### PR TITLE
0.6

### PR DESCRIPTION
**Pull request by gasparl**
I did my best to merge our codes and files smoothly. If you accept this pull request, I think everything should be fine.

Github has a [weird behavior](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch) when showing differences for pull request, but you can see all the actual changes from your current `0.6` to my `0.6` [here](https://github.com/gasparl/tidystats/commit/250cc54f34e7132ffc1da421148d6c3aaff0cf32#diff-15fed37869b32327602c4ee195fc0a4361b3d424f45dcaacf5c31d23a73f84ccR51). Or for a quick overview of the changed files see [here](https://github.com/gasparl/tidystats/commit/250cc54f34e7132ffc1da421148d6c3aaff0cf32) (but you shouldn't look at this latter for code changes because it's not yet merged with your recent commits).
Notice the relevant changes not only in `tidy_stats`, but also in `add_stats`, `helper_functions`, `read_stats`, and `tidy_stats_to_data_frame`.
These are almost all pretty small, but essential due to some new tests/functionalities.

The one relatively substantial change is in `add_stats`, see [here](https://github.com/gasparl/tidystats/blob/dab9c4b9cca5f040efbfe922ace67f0dec498624/R/add_stats.R#L263). Because `emmeans` sometimes returns `list` objects, to properly save these objects I implemented a check to see whether all list elements have `tidystats` methods, in which case it adds each list element separately. I could have done it in a way to check whether they are all `emmeans` objects, but I thought why not check for all existing methods: it may be useful, since, after all, what other reason would there be to pass a list of tidystats-compatible objects to `add_stats`. But if you wish, this can easily be amended to just check for `emmeans` objects.

### CODE REVIEW

**Comment by WillemSleegers** [comment]
Thanks @gasparl ! I'll take a look at this soon.

**Comment by WillemSleegers** [comment]
I've been checking out the `emmeans` tidying functions and I don't think the tidying is done correctly. I think your approach has been to convert data frames to lists, even though some of the columns indicating grouping variables and should therefore be stored in a group, followed by the statistics belonging to that group. 

I had already created some functions for `emmeans` (although it doesn't cover everything you found). You can take a look at for example the summary_emm function to see how I deal with groups. 

Maybe we should also meet to discuss the grouping better because I also tidied another object differently (pairwise I think). This is definitely one of the more annoying aspects of this project; having to figure out how to exactly tidy all these different analyses.

**Comment by gasparl** [comment]
Ah okay, but that seems to me too granular. Already in my version the example tables often consist of only a few rows; with yours it would typically be a single row, which is hardly sensible for a table. Then again, I'm not used to `emmeans`, maybe in real cases this is different. Anyway, this seems easy to change, it just has to be decided on. We can discuss if you want.

**Comment by WillemSleegers** [comment]
Why do you refer to tables? Tables only refer to how statistics are reported, not their underlying structure. It's more about what the statistics conceptually mean. In the case of estimated marginal means, we tend to have coefficients/terms, just like we have with standard regression, with possibly added complexity of having terms for different groups.

**Comment by gasparl** [comment]
I was just thinking of it only from the reporting perspective, but, anyway, we'll discuss.

**Pull request closed without merging**
